FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app/worker

COPY worker/requirements.txt /app/worker/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY worker /app/worker

CMD ["celery", "-A", "worker.celery_app", "worker", "--loglevel=info"]
